### ISSUE TITLE
Cannot find module '../../../colorkraken-config.js'

### ISSUE THREAD

**Issue by younesshakky** [Bouhoum/colorkraken#1]
Hello

it looks like tailwind could not find my config file due to it being statically declared inside the codebase as:

```
const colorkraken = require('../../../colorkraken-config.js' );
```
![image](https://user-images.githubusercontent.com/17964634/109983194-e4628300-7d02-11eb-9ad2-6b7dfbf2aeb1.png)

---
update: my config file name was mistyped

**Comment by Bouhoum** [comment]
I will update the files so they will be declared dynamically.
Thanks for the recommendation
